# Generated by Django 4.0.2 on 2022-04-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='physician',
        ),
    ]
