# Generated by Django 4.0.2 on 2022-04-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_prediction_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='prediction',
            name='heartDiseaseProb',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
