# Generated by Django 4.0.2 on 2022-05-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_prediction_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionToTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('chestPainType', models.CharField(choices=[('ASY', 'Asymptomatic'), ('ATA', 'Atypical Angina'), ('NAP', 'Non-Anginal Pain'), ('TA', 'Typical Angina')], max_length=10)),
                ('restingBP', models.PositiveIntegerField()),
                ('cholesterol', models.PositiveIntegerField()),
                ('fastingBS', models.IntegerField(choices=[(0, 'Otherwise'), (1, 'FastingBS > 120 mg/dl')])),
                ('restingECG', models.CharField(choices=[('LVH', 'LVH'), ('Normal', 'Normal'), ('ST', 'ST')], max_length=10)),
                ('maxHR', models.PositiveIntegerField()),
                ('exerciseAngina', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=10)),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sT_Slope', models.CharField(choices=[('Down', 'DOWN'), ('Flat', 'FLAT'), ('Up', 'UP')], max_length=10)),
                ('heartDisease', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('aiModel', models.IntegerField(choices=[(0, 'Single Model (XGB Classifier)'), (1, 'Hard Voting Ensemble Models')], max_length=50, null=True)),
                ('was_used', models.BooleanField(null=True)),
                ('prediction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.prediction')),
            ],
        ),
        migrations.DeleteModel(
            name='Physician',
        ),
    ]
