# Generated by Django 4.0.2 on 2022-06-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('last_prediction', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('last_prediction_prob', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
